### ISSUE TITLE
Use Readiness / Liveness Probes in manifests from the get go

### ISSUE THREAD

**Issue by markuszm** [azuredevcollege/chaos-eng-workshop#15]
Probe delay was implemented in the applications but not used in the k8s manifests yet. We should integrate it directly so that the result of chaos experiments are more visible.

**Comment by cdennig** [comment]
Current default values are 15sec. What would you suggest?

**Comment by markuszm** [comment]
Okay, got confused because I did not see any config in the k8s manifests. 
Maybe we could increase the default to one minute. But I guess we need to fine-tune the value going through the challenges when they are finished.

**Comment by cdennig** [comment]
Has been fixed in the deployment manifests
